# Market Scanner Configuration

# Development mode (set to true for more verbose logging)
dev_mode: false

# Number of days to look back for timeseries data (default: 882 days = ~3.5 years)
timeseries_days_lookback: 882

# Default index to use if none specified
default_index: "DIA.US"

# File paths
paths:
  # API license file containing the API key
  license_file: "license.txt"
  
  # Log file location
  log_file: "logs/scannerlog.txt"
  
  # Data files
  regions_data: "data/regions_data.csv"
  
  # Input files
  index_inclusion: "data/index_inclusion.txt"
  ticker_inclusion: "data/ticker_inclusion.txt"
  ticker_exclusion: "data/ticker_exclusion.txt"
  
  # Output directory
  output_dir: "output"
  data_dir: "data"